#All routes for the whatsapp API

###Send Message
POST http://165.22.218.192:8000/send/message HTTP/1.1
accept: * 
content-type: application/json

{
    "phone":   8459953212,
    "message": "HEY, JUST CHECKING ROUTE"
}