
#########################################
#              API - ROUTES             #
#########################################

@HOST = 165.22.218.192
@PORT = 4006
@TO  = "+919137246088"


### Check if API is working 
GET http://{{HOST}}:{{PORT}}/api HTTP/1.1

### Get QR-CODE to login 
GET http://{{HOST}}:{{PORT}}/api/qrcode HTTP/1.1
accept: * 
content-type: application/json

### Check Client status if its logged in or not
GET http://{{HOST}}:{{PORT}}/api/whatsapp/status HTTP/1.1
accept: * 
content-type: application/json


###Send Message
POST http://{{HOST}}:{{PORT}}/api/send/message HTTP/1.1
accept: * 
content-type: application/json

{
    "phone"    : {{TO}},
    "message"  : "HEY, JUST CHECKING ROUTE ASAP!"
}


###Send Image with URL
POST http://{{HOST}}:{{PORT}}/api/send/image HTTP/1.1
accept: * 
content-type: application/json

{
    "phone"     : {{TO}},
    "url"       : "https://picsum.photos/200/300",
    "caption"   : "New Image"
}

###Send Location
POST http://{{HOST}}:{{PORT}}/api/send/location HTTP/1.1
accept: * 
content-type: application/json

{
    "phone"       : {{TO}},
    "latitude"    : 19.009340,
    "longitude"   : 72.830566,
    "description" : "New Location"
}


