
#########################################
#              API - ROUTES             #
#########################################

@HOST = 165.22.218.192
@PORT = 4006
@TO  = 8459953212


### Check if API is working 
GET http://{{HOST}}:{{PORT}}/api HTTP/1.1

### Get QR-CODE to login 
GET http://{{HOST}}:{{PORT}}/api/qrcode HTTP/1.1
accept: * 
content-type: application/json

### Check Client status if its logged in or not
GET http://{{HOST}}:{{PORT}}/api/whatsapp/status HTTP/1.1
accept: * 
content-type: application/json


###Send Message
POST http://{{HOST}}:{{PORT}}/api/send/message HTTP/1.1
accept: * 
content-type: application/json

{
    "phone": {{TO}},
    "message": "HEY, JUST CHECKING ROUTE"
}


